modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory

issueTrackerURL="https://github.com/Andromander/BadBeacon/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/bad-beacon" #optional
credits="Credit to the culmination of tiny ideas" #optional
authors="Androsa" #optional
license="${mod_license}"

[[mods]] #mandatory
modId="badbeacon" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
description='''
Imagine making a Beacon one day, but instead of a Nether Star and some Obsidian, you substitute it for a Heart of the Sea and some Nether Wart Blocks.

In comes the Bad Beacon. A block with a purple light, red base, a black beam of light, and the negative effects that come with it. Build the base of Coal, Lapis Lazuli, Redstone, Nether Quartz, or Copper and pay with those similar items.
Affect everyone or just the players. Add some blocks and payment methods with a datapack.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.badbeacon]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.badbeacon]]
    modId="minecraft"
    type="required"
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"